services:
  pr:
    container_name: pr
    restart: unless-stopped
    ports:
      - "8080:8080"
    build:
      context: ./
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: postgres
      DB_SSLMODE: disable
      HTTP_PORT: 8080

  db:
    image: postgres:17.0
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
    name: local_db_data